### ISSUE TITLE
Error load MySQLdb, check if MySQLdb is installed!

### ISSUE THREAD

**Issue by maxandre82** [vsc55/ombi_sqlite_mysql#19]
Hi I followed the steps for Installing MySQL on Windows via https://docs.ombi.app/guides/mysql-installation-windows/ which was successful and i am stuck on step 3. Create and prepare tables via https://docs.ombi.app/guides/migrating-databases/#3-create-and-prepare-tables.  I am getting the following error:

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd C:\Tools\Ombi

C:\Tools\Ombi>python ombi_sqlite2mysql.py -c C:\Tools\Ombi --only_db_json --host 127.0.0.1 --db Ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Error load MySQLdb, check if MySQLdb is installed!

C:\Tools\Ombi

![image](https://user-images.githubusercontent.com/20952464/146687958-891db0c4-2c78-4282-8211-1ed40bc4ac90.png)

**Comment by vsc55** [comment]
Hi @maxandre82,
You need install plugin mysqlclient
`pip install mysqlclient`
or 
`python -m pip install mysqlclient`

2. Install the dependencies according to the operating system we use.
https://docs.ombi.app/guides/migrating-databases/#2-download-script-and-install-dependencies

**Comment by maxandre82** [comment]
Thank you so much @vsc55 that worked!

Now I'm facing the following error...

C:\Users\Administrator>cd C:\Tools\Ombi

C:\Tools\Ombi>ombi --migrate
Hello, welcome to Ombi
Valid options are:
Ombi 4.7.10
Copyright (C) 2021 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --migrate    Will run the migrations then exit the application

  --help       Display this help screen.

  --version    Display version information.



Unhandled exception. MySqlConnector.MySqlException (0x80004005): Connect Timeout expired.
 ---> MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 432
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 363
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 94
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 124
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 911
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 933
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 405
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 369
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at Ombi.Extensions.DatabaseExtensions.ConfigureMySql(DbContextOptionsBuilder options, PerDatabaseConfiguration config) in /home/runner/work/Ombi/Ombi/src/Ombi/Extensions/DatabaseExtensions.cs:line 123
   at Ombi.Extensions.DatabaseExtensions.<>c__DisplayClass2_0.<ConfigureDatabases>b__5(DbContextOptionsBuilder x) in /home/runner/work/Ombi/Ombi/src/Ombi/Extensions/DatabaseExtensions.cs:line 57
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass1_0`2.<AddDbContext>b__0(IServiceProvider p, DbContextOptionsBuilder b)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Ombi.Program.Main(String[] args) in /home/runner/work/Ombi/Ombi/src/Ombi/Program.cs:line 74
   at Ombi.Program.<Main>(String[] args)

C:\Tools\Ombi>

**Comment by vsc55** [comment]
Hi @maxandre82,
This Timeout error is due to a problem with your MySQL / MaridDB server that is not responding.
Check firewall or settings and if you can access it with a program such as: 
https://www.mysql.com/products/workbench/
https://www.heidisql.com/

**Comment by maxandre82** [comment]
Yep able to access it via workbench.

![image](https://user-images.githubusercontent.com/20952464/146692270-61ddaad3-281e-4c29-9360-88648b94c93f.png)

![image](https://user-images.githubusercontent.com/20952464/146692294-6e879a5e-a97c-428a-8839-dba0f57ac43b.png)

**Comment by vsc55** [comment]
From what I see accessing with root user, try the ombi user that you have created. 
If you can access with ombi, try to run the following command again and try the migration again. 
`C:\Tools\Ombi>python ombi_sqlite2mysql.py -c C:\Tools\Ombi --only_db_json --host 127.0.0.1 --db Ombi --user ombi --passwd ombi`

**Comment by maxandre82** [comment]
Yep, the user denied, I thought I had granted access when I created it. 

![image](https://user-images.githubusercontent.com/20952464/146701398-14c5243e-c4ea-45f3-bbd5-cc9ffa08e75f.png)

What should be the necessary perimeters
![image](https://user-images.githubusercontent.com/20952464/146701737-e7c64875-bfc6-4329-a694-2e6a99d54d23.png)


Thanks

**Comment by vsc55** [comment]
Look in the Schema Privileges tab, and if not you will have to reset the user password.

**Comment by maxandre82** [comment]
@vsc55 Thank you so Very Much!!!!

Yes resetting the password work!!!

![image](https://user-images.githubusercontent.com/20952464/146766098-9443483a-0448-4596-b4fa-5c0a1285ae21.png)

:)

**Comment by maxandre82** [comment]
For the next Step... 4.1. Data Migration (Single Database), I'm a little lost with the instruction... 

How would I generate the migration.json file, would that also be via CMD, the instruction show the following below, but I'm not sure if that is through command prompt or another application. Sorry for being a novas at that :(, I know enough, just not an expert. Thank you @vsc55 
--------------------------------------------------------------------------------------------------------------------------------------
$ python ombi_sqlite2mysql.py -c /etc/Ombi --only_manager_json
Migration tool from SQLite to MySql/MariaDB for ombi (x.x.x) By VSC55

Generate file "migration.json":
- Saving in (/etc/Ombi/migration.json)... [✓]

$ nano /etc/Ombi/migration.json

**Comment by maxandre82** [comment]
Hi @vsc55!

Question regarding 4.1. Data Migration (Single Database). Just to confirm, would I manually create the "migration.json" and add the following content to it...

{
   "OmbiDatabase": {
      "Type":"sqlite",
      "ConnectionString":"Data Source=/etc/Ombi/Ombi.db"
   },
   "SettingsDatabase": {
      "Type":"sqlite",
      "ConnectionString":"Data Source=/etc/Ombi/OmbiSettings.db"
   }
}

**Comment by maxandre82** [comment]
Migrate in progress...
Migrate complete.

C:\Tools\Ombi>python ombi_sqlite2mysql.py -c /etc/Ombi --config Migration tool from SQLite to MySql/MariaDB for ombi (x.x.x) by VSC55
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Traceback (most recent call last):
  File "C:\Tools\Ombi\ombi_sqlite2mysql.py", line 1150, in <module>
    main()
  File "C:\Tools\Ombi\ombi_sqlite2mysql.py", line 1106, in main
    _mysql_database_json_update(True)
  File "C:\Tools\Ombi\ombi_sqlite2mysql.py", line 1003, in _mysql_database_json_update
    "ConnectionString": "Server={0};Port={1};Database={2};User={3};Password={4}".format(mysql_cfg['host'], mysql_cfg['port'], mysql_cfg['db'], mysql_cfg['user'], mysql_cfg['passwd'])
TypeError: 'NoneType' object is not subscriptable

C:\Tools\Ombi>

**Comment by vsc55** [comment]
Hi @maxandre82 ,

The Path "/etc/Omb" is for linux, if your system is Windows you will have to use "C:\Tools\Ombi"

**Comment by vsc55** [comment]
Just run these commands for a standard update with a single database: 
```cmd
# python ombi_sqlite2mysql.py -c C:\Tools\Ombi --only_db_json --host 127.0.0.1 --db Ombi --user ombi --passwd ombi
# C:\Tools\Ombi\ombi.exe --migrate
# python ombi_sqlite2mysql.py -c C:\Tools\Ombi --host 127.0.0.1 --db Ombi --user ombi --passwd ombi
```
No need to edit any files manually.

**Comment by maxandre82** [comment]
You Are Man!!!!!!! 

Migration completed!!!!

Thank you soooo very much @vsc55 :):):)

**Comment by vsc55** [comment]
I'm glad it worked for you.  😄

**Comment by maxandre82** [comment]
Im soooo sorry @vsc55, i spoke too soon.... :( I should have checked the site too when I was done, I got a little to happen :(

![image](https://user-images.githubusercontent.com/20952464/146943106-b0802a29-c518-4a6c-9b85-9befb4ece700.png)

**Comment by vsc55** [comment]
Hi @maxandre82,
Is there an error in the console or in the logs?

**Comment by maxandre82** [comment]
Hey @vsc55, yes the only error im seeing in the logs is the following....

2021-12-18 01:03:31.941 -05:00 [Debug] Batch acquisition of 0 triggers
2021-12-18 01:03:46.343 -05:00 [Error] Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30

[log-20211218.txt](https://github.com/vsc55/ombi_sqlite_mysql/files/7758173/log-20211218.txt)

**Comment by vsc55** [comment]
Hi @maxandre82,
That seems like more of Ombi's mistake. It doesn't seem to be related to data migration.
You will have to open an issue in the Ombi repository.

**Comment by maxandre82** [comment]
Hey @vsc55, ok i will!.
Even thought it was working before?

Thanks @vsc55
