### ISSUE TITLE
ombi : command not found

### ISSUE THREAD

**Issue by fana13** [vsc55/ombi_sqlite_mysql#20]
In step 5 to migration : ombi --migrate
I've got this issue : ombi command not found
I tried to run command into my ombi folder (/opt/Ombi) and into the ombi_sqlite_mysql folder
Where's my mistake please ?

**Comment by vsc55** [comment]
Hi @fana13,
The linux system is case-sensitive, by default the Ombi application is written with the capital O, try as follows: 
`Ombi --migrate`

**Comment by fana13** [comment]
Thanks for your reply @vsc55, i tried with the capital O and it's same thing unfortunately.
This command was not found

**Comment by vsc55** [comment]
you can post what it returns:
`ls -la /opt/Omb`

**Comment by fana13** [comment]
This content : 
drwxr-xr-x  7 root root      4096 déc.  24 18:08 .
drwxr-xr-x 17 root root      4096 déc.  24 16:07 ..
-rw-r--r--  1 root root       272 déc.  24 12:51 appsettings.Development.json
-rw-r--r--  1 root root      2139 déc.  24 12:51 appsettings.json
drwxr-xr-x  3 root root      4096 déc.  24 12:51 ClientApp
-rw-r--r--  1 root root       389 déc.  24 18:08 database.json
-rwxr--r--  1 root root   1195200 déc.  24 12:51 libe_sqlite3.so
drwxr-xr-x  2 root root      4096 déc.  24 12:51 Logs
-rwxr-xr-x  1 root root 116989002 déc.  24 12:51 Ombi
-rw-r--r--  1 root root     14008 déc.  24 12:51 Ombi.Api.CloudService.pdb
-rw-r--r--  1 root root     16820 déc.  24 12:51 Ombi.Api.CouchPotato.pdb
-rw-r--r--  1 root root     14944 déc.  24 12:51 Ombi.Api.Discord.pdb
-rw-r--r--  1 root root     17492 déc.  24 12:51 Ombi.Api.DogNzb.pdb
-rw-r--r--  1 root root     41124 déc.  24 12:51 Ombi.Api.Emby.pdb
-rw-r--r--  1 root root     15644 déc.  24 12:51 Ombi.Api.FanartTv.pdb
-rw-r--r--  1 root root     14540 déc.  24 12:51 Ombi.Api.Github.pdb
-rw-r--r--  1 root root     13732 déc.  24 12:51 Ombi.Api.Gotify.pdb
-rw-r--r--  1 root root     16544 déc.  24 12:51 Ombi.Api.GroupMe.pdb
-rw-r--r--  1 root root     40556 déc.  24 12:51 Ombi.Api.Jellyfin.pdb
-rw-r--r--  1 root root     30796 déc.  24 12:51 Ombi.Api.Lidarr.pdb
-rw-r--r--  1 root root     16276 déc.  24 12:51 Ombi.Api.Mattermost.pdb
-rw-r--r--  1 root root     15296 déc.  24 12:51 Ombi.Api.MusicBrainz.pdb
-rw-r--r--  1 root root     14692 déc.  24 12:51 Ombi.Api.Notifications.pdb
-rw-r--r--  1 root root     17760 déc.  24 12:51 Ombi.Api.pdb
-rw-r--r--  1 root root     35580 déc.  24 12:51 Ombi.Api.Plex.pdb
-rw-r--r--  1 root root     13780 déc.  24 12:51 Ombi.Api.Pushbullet.pdb
-rw-r--r--  1 root root     13936 déc.  24 12:51 Ombi.Api.Pushover.pdb
-rw-r--r--  1 root root     25488 déc.  24 12:51 Ombi.Api.Radarr.pdb
-rw-r--r--  1 root root     15816 déc.  24 12:51 Ombi.Api.RottenTomatoes.pdb
-rw-r--r--  1 root root     18040 déc.  24 12:51 Ombi.Api.Service.pdb
-rw-r--r--  1 root root     18000 déc.  24 12:51 Ombi.Api.SickRage.pdb
-rw-r--r--  1 root root     14268 déc.  24 12:51 Ombi.Api.Slack.pdb
-rw-r--r--  1 root root     27620 déc.  24 12:51 Ombi.Api.Sonarr.pdb
-rw-r--r--  1 root root     13736 déc.  24 12:51 Ombi.Api.Telegram.pdb
-rw-r--r--  1 root root     49676 déc.  24 12:51 Ombi.Api.TheMovieDb.pdb
-rw-r--r--  1 root root     14232 déc.  24 12:51 Ombi.Api.Trakt.pdb
-rw-r--r--  1 root root     24628 déc.  24 12:51 Ombi.Api.TvMaze.pdb
-rw-r--r--  1 root root     10992 déc.  24 12:51 Ombi.Api.Twilio.pdb
-rw-r--r--  1 root root     13856 déc.  24 12:51 Ombi.Api.Webhook.pdb
-rw-r--r--  1 root root    145692 déc.  24 12:51 Ombi.Core.pdb
-rw-r--r--  1 root root    585728 déc.  24 17:15 Ombi.db
-rw-r--r--  1 root root     19408 déc.  24 12:51 Ombi.DependencyInjection.pdb
-rw-r--r--  1 root root   1052672 déc.  24 17:40 OmbiExternal.db
-rw-r--r--  1 root root     19652 déc.  24 12:51 Ombi.HealthChecks.pdb
-rw-r--r--  1 root root     24740 déc.  24 12:51 Ombi.Helpers.pdb
-rw-r--r--  1 root root     16492 déc.  24 12:51 Ombi.Hubs.pdb
-rw-r--r--  1 root root     21804 déc.  24 12:51 Ombi.Mapping.pdb
-rw-r--r--  1 root root     51852 déc.  24 12:51 Ombi.Notifications.pdb
-rw-r--r--  1 root root     10740 déc.  24 12:51 Ombi.Notifications.Templates.pdb
-rw-r--r--  1 root root    131104 déc.  24 12:51 Ombi.pdb
-rw-r--r--  1 root root     86228 déc.  24 12:51 Ombi.Schedule.pdb
-rw-r--r--  1 root root     32768 déc.  24 13:30 OmbiSettings.db
-rw-r--r--  1 root root     30668 déc.  24 12:51 Ombi.Settings.pdb
drwxr-xr-x  3 root root      4096 déc.  24 16:08 ombi_sqlite_mysql
-rw-r--r--  1 root root    263476 déc.  24 12:51 Ombi.Store.pdb
-rwxr-xr-x  1 root root  10782504 déc.  24 12:51 Ombi.Updater
-rw-r--r--  1 root root     14688 déc.  24 12:51 Ombi.Updater.pdb
-rw-r--r--  1 root root       271 déc.  24 12:51 Ombi.Updater.runtimeconfig.json
-rw-r--r--  1 root root     83935 déc.  24 12:51 Ombi.xml
drwxr-xr-x  2 root root      4096 déc.  24 12:51 Templates
drwxr-xr-x  5 root root      4096 déc.  24 12:51 wwwroot

**Comment by vsc55** [comment]
It should work since Ombi exists and has execute permission.
` -rwxr-xr-x 1 root root 116989002 déc. 24 12:51 Ombi`
Are you in the /opt/Ombi folder when you run the command?

**Update:**
Try it like this:
`./Ombi --migrate`

**Comment by fana13** [comment]
Yes i'm in.
I tried to run like this  : ./Ombi --migrate and i've got a big issue

```
Valid options are:
Ombi 4.8.0
Copyright (C) 2021 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --migrate    Will run the migrations then exit the application

  --help       Display this help screen.

  --version    Display version information.



Unhandled exception. MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 432
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 363
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 94
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 124
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 911
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 405
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 369
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at Ombi.Extensions.DatabaseExtensions.ConfigureMySql(DbContextOptionsBuilder options, PerDatabaseConfiguration config) in /home/runner/work/Ombi/Ombi/src/Ombi/Extensions/DatabaseExtensions.cs:line 123
   at Ombi.Extensions.DatabaseExtensions.<>c__DisplayClass2_0.<ConfigureDatabases>b__5(DbContextOptionsBuilder x) in /home/runner/work/Ombi/Ombi/src/Ombi/Extensions/DatabaseExtensions.cs:line 57
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass1_0`2.<AddDbContext>b__0(IServiceProvider p, DbContextOptionsBuilder b)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Ombi.Program.Main(String[] args) in /home/runner/work/Ombi/Ombi/src/Ombi/Program.cs:line 74
   at Ombi.Program.<Main>(String[] args)
```

**Comment by vsc55** [comment]
It is telling you that the mysql server you have specified is not working.

The procedure is very simple, you only have to execute 3 commands:
```bash
# python ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host 127.0.0.1 --db Ombi --user ombi --passwd ombi
# Ombi.exe --migrate
# python ombi_sqlite2mysql.py -c /etc/Ombi --host 127.0.0.1 --db Ombi --user ombi --passwd ombi
```
Replace "/etc/Ombi" with the location where ombi saves your configuration and sqlite databases, and modify the data corresponding to your MySQL/MariaDB server.

**Comment by fana13** [comment]
I did a mysql/mariadb fresh install.
And now with  ./Ombi --migrate command it works !
Many thanks :)

**Comment by jscottelblein** [comment]
I ran into this as well (using the LinuxServer.io) container. It worked by passing the full path:

    /opt/ombi/Ombi --migrate
