### ISSUE TITLE
Migration to mysql error v.4.12.0

### ISSUE THREAD

**Issue by fana13** [vsc55/ombi_sqlite_mysql#23]
**Describe the bug**
On migration to mysql step, i've got multiple errors

**To Reproduce**
python ombi_sqlite2mysql.py -c /etc/Ombi --host 192.168.1.100 --db Ombi --user ombi --passwd ombi

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958] 4.12.0
- Database Type: MYSQL

```
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55

Generate file "database.json":
- Saving in (/opt/Ombi/database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [############################################################] 1/1
Read tables [✓]

Check migration.json:
- OmbiDatabase [SQLite >> Migrate]
- SettingsDatabase [SQLite >> Migrate]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- OmbiDatabase      [############################################################] 1246/1246
- SettingsDatabase  [############################################################] 25/25
- ExternalDatabase  [############################################################] 12641/12641

Start clean tables:
- [CLEAN ] -> ApplicationConfiguration -> rows: 4
- [CLEAN ] -> AspNetRoles -> rows: 13
- [CLEAN ] -> AspNetUserRoles -> rows: 25
- [CLEAN ] -> AspNetUsers -> rows: 9
- [CLEAN ] -> ChildRequests -> rows: 18
- [CLEAN ] -> EpisodeRequests -> rows: 386
- [CLEAN ] -> GlobalSettings -> rows: 12
- [CLEAN ] -> LidarrAlbumCache -> rows: 1003
- [CLEAN ] -> LidarrArtistCache -> rows: 105
- [CLEAN ] -> MobileDevices -> rows: 4
- [CLEAN ] -> NotificationTemplates -> rows: 120
- [CLEAN ] -> NotificationUserId -> rows: 5
- [CLEAN ] -> PlexEpisode -> rows: 7139
- [CLEAN ] -> PlexSeasonsContent -> rows: 474
- [CLEAN ] -> RequestLog -> rows: 264
- [CLEAN ] -> RequestQueue -> rows: 22
- [CLEAN ] -> RequestSubscription -> rows: 2
- [CLEAN ] -> SeasonRequests -> rows: 32
- [CLEAN ] -> SickRageCache -> rows: 24
- [CLEAN ] -> SonarrCache -> rows: 83
- [CLEAN ] -> SonarrEpisodeCache -> rows: 2545
- [CLEAN ] -> TvRequests -> rows: 18
- [CLEAN ] -> UserNotificationPreferences -> rows: 57
- [CLEAN ] -> UserQualityProfiles -> rows: 8
- [BACKUP] -> __EFMigrationsHistory
- [SKIP  ] -> __EFMigrationsHistory -> rows: 35

- Running   [############################################################] 26/26
Clean tables [✓]

Start Migration:
- Preparing [############################################################] 13924/13924
ombi_sqlite2mysql.py:503: Warning: (1265, "Data truncated for column 'LastLoggedIn' at row 1")
  cur.execute(i)
ombi_sqlite2mysql.py:503: Warning: (1265, "Data truncated for column 'RequestedDate' at row 1")
  cur.execute(i)
ombi_sqlite2mysql.py:503: Warning: (1265, "Data truncated for column 'MarkedAsAvailable' at row 1")
  cur.execute(i)
- Running   [............................................................] 27/13822
* MySQL Error [1054]: Unknown column 'Has4KRequest' in 'field list'
* Error Query: INSERT INTO `MovieRequests` (`Id`, `Title`, `Approved`, `MarkedAsApproved`, `RequestedDate`, `Available`, `MarkedAsAvailable`, `RequestedUserId`, `Denied`, `MarkedAsDenied`, `DeniedReason`, `RequestType`, `RequestedByAlias`, `ImdbId`, `Overview`, `PosterPath`, `ReleaseDate`, `DigitalReleaseDate`, `Status`, `Background`, `TheMovieDbId`, `IssueId`, `RootPathOverride`, `QualityOverride`, `LangCode`, `Has4KRequest`, `Approved4K`, `Available4K`, `Denied4K`, `DeniedReason4K`, `MarkedAsApproved4K`, `MarkedAsAvailable4K`, `MarkedAsDenied4K`, `RequestedDate4k`) VALUES(1,'Bloodshot',1,'2020-05-28 14:42:02.0739095','2020-05-25 08:46:15.6458824',1,'2020-05-28 15:30:01.1707912','85aa0f0a-090d-4f8f-adf5-f5d5f9cf1966',0,'0001-01-01 00:00:00',NULL,1,NULL,'tt1634106','Ray Garrison un soldat mort au combat ressuscité par l''entrepreneur en armement Rising Spirit Technologies grâce à la nanotechnologie. Souffrant d''une perte totale de mémoire mais désormais doté de toute une gamme de nouvelles capacités, Ray a du mal à renouer avec qui il était tout en apprenant quelle sorte d''arme il est devenu... Aidé par une équipe de camarades combattants augmentés sous le nom de code Chainsaw.','/6VRhjfA495M6viOPL4aF1cIlGfE.jpg','2020-03-05 00:00:00','2020-03-24 00:00:00','Released','/ocUrMYbdjknu2TwzMHKT9PBBQRw.jpg',338762,NULL,0,0,'fr',0,0,0,NULL,NULL,'0001-01-01 00:00:00',NULL,'0001-01-01 00:00:00','0001-01-01 00:00:00');

- Running   [............................................................] 28/13822
* MySQL Error [1054]: Unknown column 'Has4KRequest' in 'field list'
* Error Query: INSERT INTO `MovieRequests` (`Id`, `Title`, `Approved`, `MarkedAsApproved`, `RequestedDate`, `Available`, `MarkedAsAvailable`, `RequestedUserId`, `Denied`, `MarkedAsDenied`, `DeniedReason`, `RequestType`, `RequestedByAlias`, `ImdbId`, `Overview`, `PosterPath`, `ReleaseDate`, `DigitalReleaseDate`, `Status`, `Background`, `TheMovieDbId`, `IssueId`, `RootPathOverride`, `QualityOverride`, `LangCode`, `Has4KRequest`, `Approved4K`, `Available4K`, `Denied4K`, `DeniedReason4K`, `MarkedAsApproved4K`, `MarkedAsAvailable4K`, `MarkedAsDenied4K`, `RequestedDate4k`) VALUES(2,'Scooby !',1,'2020-05-28 14:41:56.2514392','2020-05-25 08:46:21.6754943',1,'2020-07-26 23:30:01.2311318','85aa0f0a-090d-4f8f-adf5-f5d5f9cf1966',0,'0001-01-01 00:00:00',NULL,1,NULL,'tt3152592','Démarrez la Mystery Machine ! Scooby-Doo et ses amis luttent à nouveau contre le crime dans une toute nouvelle aventure.','/qOK52Iw8wIeI8MnHmP9QRypQcyV.jpg','2020-05-15 00:00:00','2020-05-15 00:00:00','Released','/fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg',385103,NULL,0,0,'fr',0,0,0,NULL,NULL,'0001-01-01 00:00:00',NULL,'0001-01-01 00:00:00','0001-01-01 00:00:00');
```

**Comment by vsc55** [comment]
Hi @fana13,

Did you run ```./Ombi --migrate``` with version 4.12.0 or an earlier version of ombi?

**Comment by vsc55** [comment]
Hi @fana13,
I have updated right now to version 4.12.0 and it gives me an error related to those columns.
Looks like an omb bug.

**Comment by vsc55** [comment]
https://github.com/Ombi-app/Ombi/issues/4508

**Comment by fana13** [comment]
I migrated to MariaDB 10.6.7 database server like @tidusjar specified
I updated in last Ombi 4.12.3 version
And now i've got these errors : 
```
 python ombi_sqlite2mysql.py -c /opt/Ombi --host 127.0.0.1 --db Ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55

Generate file "database.json":
- Saving in (/opt/Ombi/database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [............................................................] 0/1
- Error: Table "__EFMigrationsHistory" requiered is not exist in the server MySQL!!!
Read tables [!!]

MySQL > Disconnecting... [✓]
```

**Comment by fana13** [comment]
If i try with the Ombi 4.12.0 version, always with last MariaDB 10.6.7 version, i've got these errors : 

```
python ombi_sqlite2mysql.py -c /opt/Ombi --host 127.0.0.1 --db Ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55

Generate file "database.json":
- Saving in (/opt/Ombi/database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [############################################################] 1/1
Read tables [✓]

Check migration.json:
- OmbiDatabase [SQLite >> Migrate]
- SettingsDatabase [SQLite >> Migrate]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- OmbiDatabase      [############################################################] 1259/1259
- SettingsDatabase  [############################################################] 26/26
- ExternalDatabase  [############################################################] 12715/12715

Start clean tables:

* MySQL Error [1064]: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SELECT CONCAT('SELECT * FROM (',GROUP_CONCAT(CONCAT('SELECT ',QUOTE(tb),' `Ta...' at line 1
* Error Query: SET group_concat_max_len = 1024 * 1024 * 100;SELECT CONCAT('SELECT * FROM (',GROUP_CONCAT(CONCAT('SELECT ',QUOTE(tb),' `Table`, COUNT(1) `Rows` FROM ',db,'.',tb) SEPARATOR ' UNION '),') A ORDER BY `Table` ASC ;')INTO @sql FROM (SELECT table_schema db,table_name tb FROM information_schema.tables WHERE table_schema = DATABASE() and table_name not LIKE '%_migration_backup_%') A;PREPARE s FROM @sql;


* MySQL Error [1064]: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DEALLOCATE PREPARE s' at line 1
* Error Query: EXECUTE s; DEALLOCATE PREPARE s;

Traceback (most recent call last):
  File "ombi_sqlite2mysql.py", line 1250, in <module>
    main()
  File "ombi_sqlite2mysql.py", line 1221, in main
    if _mysql_tables_clean():
  File "ombi_sqlite2mysql.py", line 741, in _mysql_tables_clean
    for table, count in return_query[1]:
TypeError: 'NoneType' object is not iterable
```

**Comment by vsc55** [comment]
Hi @fana13,
With the mysql database empty, does executing ```./Ombi --migrate``` give you an error?

**Comment by fana13** [comment]
Hi @vsc55 ,

Nope, no error 
```
./Ombi --migrate
Hello, welcome to Ombi
Valid options are:
Ombi 4.12.4
Copyright (C) 2022 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --migrate    Will run the migrations then exit the application

  --help       Display this help screen.

  --version    Display version information.



Migrate in progress...
Migrate complete.
```

**Comment by Fyb3roptik** [comment]
This is happening on a fresh install for me. Super irritating!

**Comment by vsc55** [comment]
Hi @Fyb3roptik,
Yes it is a bug with the new versions of mysql, as soon as I have time I will look at it.

**Comment by Fyb3roptik** [comment]
All good! I will just wait to migrate haha

**Comment by vsc55** [comment]
Hi @Fyb3roptik,
are you using mysql or mariadb?
what version is it?

**Comment by vsc55** [comment]
Hi @Fyb3roptik and @fana13.
I have been testing with the following versions of mysql and mariaDB (running it from docker) and I cannot reproduce the error.

Ombi 4.13.0

**MariaDB:**
- 10.4.24-MariaDB-1:10.4.24+maria~focal - OK
- 10.5.15-MariaDB-1:10.5.15+maria~focal - OK
- 10.6.7-MariaDB-1:10.6.7+maria~focal = OK

**MySQL:**
- 5.7.37 - OK
- 8.0.28 - OK

What operating system are you running the database on?

**Comment by Fyb3roptik** [comment]
I had figured out my issue was I was running --migrate without having started ombi after generating the JSON. For me I had to 

1. Generate the migrate and database JSON files
2. Start ombi and get to the initial screen
3. Stop ombi
4. Run the --migrate
5. Run the python scripts


This fixed it for me

**Comment by vsc55** [comment]
Hi @Fyb3roptik,
There is no need to start ombi, running --migrate directly is enough.
This would be the procedure:
1. ```# python3 ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host 192.168.1.100 --db Ombi --user ombi --passwd ombi```
2. ```# Ombi --migrate```
3. ```# python3 ombi_sqlite2mysql.py -c /etc/Ombi --host 192.168.1.100 --db Ombi --user ombi --passwd ombi```

**Comment by Fyb3roptik** [comment]
Those directions do not work. I had to do it my way in order for it to process correctly

**Comment by Fyb3roptik** [comment]
Just running --migrate wasn't enough

**Comment by fana13** [comment]
> Hi @Fyb3roptik and @fana13. I have been testing with the following versions of mysql and mariaDB (running it from docker) and I cannot reproduce the error.
> 
> Ombi 4.13.0
> 
> **MariaDB:**
> 
>     * 10.4.24-MariaDB-1:10.4.24+maria~focal - OK
> 
>     * 10.5.15-MariaDB-1:10.5.15+maria~focal - OK
> 
>     * 10.6.7-MariaDB-1:10.6.7+maria~focal = OK
> 
> 
> **MySQL:**
> 
>     * 5.7.37 - OK
> 
>     * 8.0.28 - OK
> 
> 
> What operating system are you running the database on?

Hi @vsc55 , my mariadb server version : MariaDB 10.6.7 database server
Hi @Fyb3roptik i tried your tip but still don't work for me, glad for you anyway !

**Comment by vsc55** [comment]
@fana13,
What operating system do you use where you have the database installed?
What version of Ombi are you using?

**Comment by fana13** [comment]
Debian 10 and last ombi version

**Comment by vsc55** [comment]
Hi @fana13,
I just did a clean install of debian 10 and MariaDB 10.6.7-MariaDB-1:10.6.7+maria~buster and I can't reproduce the error.

```bash
 # ./Ombi --migrate
Hello, welcome to Ombi
Valid options are:
Ombi 4.13.0
Copyright (C) 2022 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --migrate    Will run the migrations then exit the application

  --help       Display this help screen.

  --version    Display version information.



Migrate in progress...
Migrate complete.
# python3 ombi_sqlite2mysql.py -c /123/ombi/dbv4 --host 192.168.0.150 --port 3306 --db Ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55

Generate file "database.json":
- Saving in (/123/ombi/dbv4/database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [############################################################] 1/1
Read tables [✓]

Check migration.json:
- OmbiDatabase [SQLite >> Migrate]
- SettingsDatabase [SQLite >> Migrate]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- OmbiDatabase      [############################################################] 197/197
- SettingsDatabase  [############################################################] 17/17
- ExternalDatabase  [############################################################] 9/9

Start clean tables:
- [CLEAN ] -> AspNetRoles -> rows: 1
- [BACKUP] -> __EFMigrationsHistory
- [SKIP  ] -> __EFMigrationsHistory -> rows: 20

- Running   [############################################################] 3/3
Clean tables [✓]

Start Migration:
- Preparing [############################################################] 235/235
- Running   [############################################################] 178/178
- Checking  [############################################################] 46/46
Migration [✓]

MySQL > Disconnecting... [✓]
```

Do you have the generic configuration of mariadb or have you made any modifications?

**Comment by Fyb3roptik** [comment]
Mine was Ubuntu 20.04 and Mariadb 13.3 (default in Ubuntu) not docker. It was a fresh install

**Comment by fana13** [comment]
> Hi @fana13, I just did a clean install of debian 10 and MariaDB 10.6.7-MariaDB-1:10.6.7+maria~buster and I can't reproduce the error.
> 
> ```shell
>  # ./Ombi --migrate
> Hello, welcome to Ombi
> Valid options are:
> Ombi 4.13.0
> Copyright (C) 2022 Ombi
> 
>   --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
>                URL prefixes to which the server should respond. For example,
>                http://localhost:123. Use "localhost" to indicate that the server
>                should listen for requests on any IP address or hostname using
>                the specified port and protocol (for example,
>                http://localhost:5000). The protocol (http:// or https://) must
>                be included with each URL. Supported formats vary between
>                servers.
> 
>   --storage    Storage path, where we save the logs and database
> 
>   --baseurl    The base URL for reverse proxy scenarios
> 
>   --demo       Demo mode, you will never need to use this, fuck that fruit
>                company...
> 
>   --migrate    Will run the migrations then exit the application
> 
>   --help       Display this help screen.
> 
>   --version    Display version information.
> 
> 
> 
> Migrate in progress...
> Migrate complete.
> # python3 ombi_sqlite2mysql.py -c /123/ombi/dbv4 --host 192.168.0.150 --port 3306 --db Ombi --user ombi --passwd ombi
> Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55
> 
> Generate file "database.json":
> - Saving in (/123/ombi/dbv4/database.json)... [✓]
> 
> MySQL > Connecting... [✓]
> - Reading   [############################################################] 1/1
> Read tables [✓]
> 
> Check migration.json:
> - OmbiDatabase [SQLite >> Migrate]
> - SettingsDatabase [SQLite >> Migrate]
> - ExternalDatabase [SQLite >> Migrate]
> 
> Dump SQLite:
> - OmbiDatabase      [############################################################] 197/197
> - SettingsDatabase  [############################################################] 17/17
> - ExternalDatabase  [############################################################] 9/9
> 
> Start clean tables:
> - [CLEAN ] -> AspNetRoles -> rows: 1
> - [BACKUP] -> __EFMigrationsHistory
> - [SKIP  ] -> __EFMigrationsHistory -> rows: 20
> 
> - Running   [############################################################] 3/3
> Clean tables [✓]
> 
> Start Migration:
> - Preparing [############################################################] 235/235
> - Running   [############################################################] 178/178
> - Checking  [############################################################] 46/46
> Migration [✓]
> 
> MySQL > Disconnecting... [✓]
> ```
> 
> Do you have the generic configuration of mariadb or have you made any modifications?

No, nothing i have installed mariadb only to this migration.
I really don't understand

python3 ombi_sqlite2mysql.py -c /opt/Ombi --host 192.168.0.112 --db Ombi --user ombi --passwd ombi

give me :
```

Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55

Generate file "database.json":
- Saving in (/opt/Ombi/database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [############################################################] 1/1
Read tables [✓]

Check migration.json:
- OmbiDatabase [SQLite >> Migrate]
- SettingsDatabase [SQLite >> Migrate]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- OmbiDatabase      [############################################################] 1259/1259
- SettingsDatabase  [############################################################] 26/26
- ExternalDatabase  [############################################################] 13202/13202

Start clean tables:

* MySQL Error [1064]: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SELECT CONCAT('SELECT * FROM (',GROUP_CONCAT(CONCAT('SELECT ',QUOTE(tb),' `Ta...' at line 1
* Error Query: SET group_concat_max_len = 1024 * 1024 * 100;SELECT CONCAT('SELECT * FROM (',GROUP_CONCAT(CONCAT('SELECT ',QUOTE(tb),' `Table`, COUNT(1) `Rows` FROM ',db,'.',tb) SEPARATOR ' UNION '),') A ORDER BY `Table` ASC ;')INTO @sql FROM (SELECT table_schema db,table_name tb FROM information_schema.tables WHERE table_schema = DATABASE() and table_name not LIKE '%_migration_backup_%') A;PREPARE s FROM @sql;


* MySQL Error [1064]: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DEALLOCATE PREPARE s' at line 1
* Error Query: EXECUTE s; DEALLOCATE PREPARE s;

Traceback (most recent call last):
  File "ombi_sqlite2mysql.py", line 1250, in <module>
    main()
  File "ombi_sqlite2mysql.py", line 1221, in main
    if _mysql_tables_clean():
  File "ombi_sqlite2mysql.py", line 741, in _mysql_tables_clean
    for table, count in return_query[1]:
TypeError: 'NoneType' object is not iterable
```

**Comment by vsc55** [comment]
Hi @fana13,

It is a problem with the version of the python3-mysqldb library (1.3.10-2) that is installed from apt in debian.
The solution is to uninstall and install mysqlclient-2.1.0 with pip. 
```bash
apt-get remove  python3-mysqldb
pip3 install mysqlclient
```

**Comment by fana13** [comment]
Wow this is it !
Perfect, you're the best, many thanks !!

**Comment by vsc55** [comment]
Thanks to you for the info.
Now I update the documentation.
