### ISSUE TITLE
DB Migration Failure on Windows

### ISSUE THREAD

**Issue by MikeFalcor** [vsc55/ombi_sqlite_mysql#30]
All prep steps completed. When I try to run the command
`python ombi_sqlite2mysql_multi.py -c C:\Ombi`

Return is:
```
Migration tool from SQLite to Multi MySql/MariaDB for ombi (1.0.2) By VSC55

- Processing DataBase (OmbiDatabase)...
  -------------------

- Saving in (C:\Ombi\migration.json)... [✓]
Traceback (most recent call last):
  File "C:\Ombi\ombi_sqlite2mysql_multi.py", line 331, in <module>
    main()
  File "C:\Ombi\ombi_sqlite2mysql_multi.py", line 270, in main
    ombi_sqlite2mysql._clean_end_process()
  File "C:\Ombi\ombi_sqlite2mysql.py", line 343, in _clean_end_process
    _clean_fix_insert_mysql()
  File "C:\Ombi\ombi_sqlite2mysql.py", line 378, in _clean_fix_insert_mysql
    fix_insert[table_name]['mysql'] = {
KeyError: '__EFMigrationsHistory'
```

It creates a migration.json, but it is incomplete and the process is aborted.

What am I doing wrong?

**Comment by vsc55** [comment]
Hi @MikeFalcor.
What version of python to use?

**Comment by MikeFalcor** [comment]
3.9.7 as reported via --version:
`C:\Users\Master>python --version
Python 3.9.7`

**Comment by vsc55** [comment]
Hi @MikeFalcor,

I have tried to reproduce the problem but I have not succeeded.
It seems to be a problem with your system.

Do you want to export to a single database or separate the data into different databases?
I see that you are using ombi_sqlite2mysql_multi, which is used to export the data to multiple different databases.

**Comment by MikeFalcor** [comment]
Uh...OK. So... What am I supposed to do?

**Comment by MikeFalcor** [comment]
Yes, different DBs. Sorry, I didn't see your edit until just now.

**Comment by CalebW317** [comment]
Hi, Mike. Did you ever find a solution to this? I am having the exact same issue trying to migrate multiple DBs and I am not sure why exactly the code is getting hung up.

**Comment by MikeFalcor** [comment]
No. And since I was getting exasperated by this AND because I wound up rebuilding the computer and using docker for everything ARRs related, I wound up switching to a different request system. No looking back...

**Comment by CalebW317** [comment]
I ended up getting it working but I am curious which request system you went for. Was it  Overseerr?

**Comment by MikeFalcor** [comment]
Indeed it was. I didn't want to 'advertise' a different system, sorry.
